### ISSUE TITLE
Update realm version

### ISSUE THREAD

**Issue by karloff123** [markcdb/RealmManager#1]
Hi,

Can you please support the latest version of realmSwift? Please see my terminal logs.

- `RealmSwift` required by `Podfile`
- `RealmSwift (= 3.0.2)` required by `Podfile.lock`
- `RealmSwift (~> 2.6.2)` required by `RealmManager (1.0.7)`

Thank you!

**Comment by mericksters13** [comment]
removed version constraint on 4d1a639, closed.
